export type AllCountriesWorld = {
  id: number;
  name: string;
  initials: string;
  acronym: string;
  code: string;
};

export const allCountriesWorld: AllCountriesWorld[] = [
  {
    id: 1,
    name: "Afeganistão",
    initials: "AF",
    acronym: "AFG",
    code: "004",
  },
  {
    id: 2,
    name: "África do Sul",
    initials: "ZA",
    acronym: "ZAF",
    code: "710",
  },
  {
    id: 3,
    name: "Albânia",
    initials: "AL",
    acronym: "ALB",
    code: "008",
  },
  {
    id: 4,
    name: "Alemanha",
    initials: "DE",
    acronym: "DEU",
    code: "276",
  },
  {
    id: 5,
    name: "Andorra",
    initials: "AD",
    acronym: "AND",
    code: "020",
  },
  {
    id: 6,
    name: "Angola",
    initials: "AO",
    acronym: "AGO",
    code: "024",
  },
  {
    id: 7,
    name: "Anguilla",
    initials: "AI",
    acronym: "AIA",
    code: "660",
  },
  {
    id: 8,
    name: "Antártida",
    initials: "AQ",
    acronym: "ATA",
    code: "010",
  },
  {
    id: 9,
    name: "Antígua e Barbuda",
    initials: "AG",
    acronym: "ATG",
    code: "028",
  },
  {
    id: 10,
    name: "Antilhas Holandesas",
    initials: "AN",
    acronym: "ANT",
    code: "530",
  },
  {
    id: 11,
    name: "Arábia Saudita",
    initials: "SA",
    acronym: "SAU",
    code: "682",
  },
  {
    id: 12,
    name: "Argélia",
    initials: "DZ",
    acronym: "DZA",
    code: "012",
  },
  {
    id: 13,
    name: "Argentina",
    initials: "AR",
    acronym: "ARG",
    code: "032",
  },
  {
    id: 14,
    name: "Armênia",
    initials: "AM",
    acronym: "ARM",
    code: "51",
  },
  {
    id: 15,
    name: "Aruba",
    initials: "AW",
    acronym: "ABW",
    code: "533",
  },
  {
    id: 16,
    name: "Austrália",
    initials: "AU",
    acronym: "AUS",
    code: "036",
  },
  {
    id: 17,
    name: "Áustria",
    initials: "AT",
    acronym: "AUT",
    code: "040",
  },
  {
    id: 18,
    name: "Azerbaijão",
    initials: "AZ  ",
    acronym: "AZE",
    code: "31",
  },
  {
    id: 19,
    name: "Bahamas",
    initials: "BS",
    acronym: "BHS",
    code: "044",
  },
  {
    id: 20,
    name: "Bahrein",
    initials: "BH",
    acronym: "BHR",
    code: "048",
  },
  {
    id: 21,
    name: "Bangladesh",
    initials: "BD",
    acronym: "BGD",
    code: "050",
  },
  {
    id: 22,
    name: "Barbados",
    initials: "BB",
    acronym: "BRB",
    code: "052",
  },
  {
    id: 23,
    name: "Belarus",
    initials: "BY",
    acronym: "BLR",
    code: "112",
  },
  {
    id: 24,
    name: "Bélgica",
    initials: "BE",
    acronym: "BEL",
    code: "056",
  },
  {
    id: 25,
    name: "Belize",
    initials: "BZ",
    acronym: "BLZ",
    code: "084",
  },
  {
    id: 26,
    name: "Benin",
    initials: "BJ",
    acronym: "BEN",
    code: "204",
  },
  {
    id: 27,
    name: "Bermudas",
    initials: "BM",
    acronym: "BMU",
    code: "060",
  },
  {
    id: 28,
    name: "Bolívia",
    initials: "BO",
    acronym: "BOL",
    code: "068",
  },
  {
    id: 29,
    name: "Bósnia-Herzegóvina",
    initials: "BA",
    acronym: "BIH",
    code: "070",
  },
  {
    id: 30,
    name: "Botsuana",
    initials: "BW",
    acronym: "BWA",
    code: "072",
  },
  {
    id: 31,
    name: "Brasil",
    initials: "BR",
    acronym: "BRA",
    code: "076",
  },
  {
    id: 32,
    name: "Brunei",
    initials: "BN",
    acronym: "BRN",
    code: "096",
  },
  {
    id: 33,
    name: "Bulgária",
    initials: "BG",
    acronym: "BGR",
    code: "100",
  },
  {
    id: 34,
    name: "Burkina Fasso",
    initials: "BF",
    acronym: "BFA",
    code: "854",
  },
  {
    id: 35,
    name: "Burundi",
    initials: "BI",
    acronym: "BDI",
    code: "108",
  },
  {
    id: 36,
    name: "Butão",
    initials: "BT",
    acronym: "BTN",
    code: "064",
  },
  {
    id: 37,
    name: "Cabo Verde",
    initials: "CV",
    acronym: "CPV",
    code: "132",
  },
  {
    id: 38,
    name: "Camarões",
    initials: "CM",
    acronym: "CMR",
    code: "120",
  },
  {
    id: 39,
    name: "Camboja",
    initials: "KH",
    acronym: "KHM",
    code: "116",
  },
  {
    id: 40,
    name: "Canadá",
    initials: "CA",
    acronym: "CAN",
    code: "124",
  },
  {
    id: 41,
    name: "Cazaquistão",
    initials: "KZ",
    acronym: "KAZ",
    code: "398",
  },
  {
    id: 42,
    name: "Chade",
    initials: "TD",
    acronym: "TCD",
    code: "148",
  },
  {
    id: 43,
    name: "Chile",
    initials: "CL",
    acronym: "CHL",
    code: "152",
  },
  {
    id: 44,
    name: "China",
    initials: "CN",
    acronym: "CHN",
    code: "156",
  },
  {
    id: 45,
    name: "Chipre",
    initials: "CY",
    acronym: "CYP",
    code: "196",
  },
  {
    id: 46,
    name: "Cingapura",
    initials: "SG",
    acronym: "SGP",
    code: "702",
  },
  {
    id: 47,
    name: "Colômbia",
    initials: "CO",
    acronym: "COL",
    code: "170",
  },
  {
    id: 48,
    name: "Congo",
    initials: "CG",
    acronym: "COG",
    code: "178",
  },
  {
    id: 49,
    name: "Coréia do Norte",
    initials: "KP",
    acronym: "PRK",
    code: "408",
  },
  {
    id: 50,
    name: "Coréia do Sul",
    initials: "KR",
    acronym: "KOR",
    code: "410",
  },
  {
    id: 51,
    name: "Costa do Marfim",
    initials: "CI",
    acronym: "CIV",
    code: "384",
  },
  {
    id: 52,
    name: "Costa Rica",
    initials: "CR",
    acronym: "CRI",
    code: "188",
  },
  {
    id: 53,
    name: "Croácia (Hrvatska)",
    initials: "HR",
    acronym: "HRV",
    code: "191",
  },
  {
    id: 54,
    name: "Cuba",
    initials: "CU",
    acronym: "CUB",
    code: "192",
  },
  {
    id: 55,
    name: "Dinamarca",
    initials: "DK",
    acronym: "DNK",
    code: "208",
  },
  {
    id: 56,
    name: "Djibuti",
    initials: "DJ",
    acronym: "DJI",
    code: "262",
  },
  {
    id: 57,
    name: "Dominica",
    initials: "DM",
    acronym: "DMA",
    code: "212",
  },
  {
    id: 58,
    name: "Egito",
    initials: "EG",
    acronym: "EGY",
    code: "818",
  },
  {
    id: 59,
    name: "El Salvador",
    initials: "SV",
    acronym: "SLV",
    code: "222",
  },
  {
    id: 60,
    name: "Emirados Árabes Unidos",
    initials: "AE",
    acronym: "ARE",
    code: "784",
  },
  {
    id: 61,
    name: "Equador",
    initials: "EC",
    acronym: "ECU",
    code: "218",
  },
  {
    id: 62,
    name: "Eritréia",
    initials: "ER",
    acronym: "ERI",
    code: "232",
  },
  {
    id: 63,
    name: "Eslováquia",
    initials: "SK",
    acronym: "SVK",
    code: "703",
  },
  {
    id: 64,
    name: "Eslovênia",
    initials: "SI",
    acronym: "SVN",
    code: "705",
  },
  {
    id: 65,
    name: "Espanha",
    initials: "ES",
    acronym: "ESP",
    code: "724",
  },
  {
    id: 66,
    name: "Estados Unidos",
    initials: "US",
    acronym: "USA",
    code: "840",
  },
  {
    id: 67,
    name: "Estônia",
    initials: "EE",
    acronym: "EST",
    code: "233",
  },
  {
    id: 68,
    name: "Etiópia",
    initials: "ET",
    acronym: "ETH",
    code: "231",
  },
  {
    id: 69,
    name: "Fiji",
    initials: "FJ",
    acronym: "FJI",
    code: "242",
  },
  {
    id: 70,
    name: "Filipinas",
    initials: "PH",
    acronym: "PHL",
    code: "608",
  },
  {
    id: 71,
    name: "Finlândia",
    initials: "FI",
    acronym: "FIN",
    code: "246",
  },
  {
    id: 72,
    name: "França",
    initials: "FR",
    acronym: "FRA",
    code: "250",
  },
  {
    id: 73,
    name: "Gabão",
    initials: "GA",
    acronym: "GAB",
    code: "266",
  },
  {
    id: 74,
    name: "Gâmbia",
    initials: "GM",
    acronym: "GMB",
    code: "270",
  },
  {
    id: 75,
    name: "Gana",
    initials: "GH",
    acronym: "GHA",
    code: "288",
  },
  {
    id: 76,
    name: "Geórgia",
    initials: "GE",
    acronym: "GEO",
    code: "268",
  },
  {
    id: 77,
    name: "Gibraltar",
    initials: "GI",
    acronym: "GIB",
    code: "292",
  },
  {
    id: 78,
    name: "Grã-Bretanha (Reino Unido, UK)",
    initials: "GB",
    acronym: "GBR",
    code: "826",
  },
  {
    id: 79,
    name: "Granada",
    initials: "GD",
    acronym: "GRD",
    code: "308",
  },
  {
    id: 80,
    name: "Grécia",
    initials: "GR",
    acronym: "GRC",
    code: "300",
  },
  {
    id: 81,
    name: "Groelândia",
    initials: "GL",
    acronym: "GRL",
    code: "304",
  },
  {
    id: 82,
    name: "Guadalupe",
    initials: "GP",
    acronym: "GLP",
    code: "312",
  },
  {
    id: 83,
    name: "Guam (Território dos Estados Unidos)",
    initials: "GU",
    acronym: "GUM",
    code: "316",
  },
  {
    id: 84,
    name: "Guatemala",
    initials: "GT",
    acronym: "GTM",
    code: "320",
  },
  {
    id: 85,
    name: "Guernsey",
    initials: "G",
    acronym: "GGY",
    code: "832",
  },
  {
    id: 86,
    name: "Guiana",
    initials: "GY",
    acronym: "GUY",
    code: "328",
  },
  {
    id: 87,
    name: "Guiana Francesa",
    initials: "GF",
    acronym: "GUF",
    code: "254",
  },
  {
    id: 88,
    name: "Guiné",
    initials: "GN",
    acronym: "GIN",
    code: "324",
  },
  {
    id: 89,
    name: "Guiné Equatorial",
    initials: "GQ",
    acronym: "GNQ",
    code: "226",
  },
  {
    id: 90,
    name: "Guiné-Bissau",
    initials: "GW",
    acronym: "GNB",
    code: "624",
  },
  {
    id: 91,
    name: "Haiti",
    initials: "HT",
    acronym: "HTI",
    code: "332",
  },
  {
    id: 92,
    name: "Holanda",
    initials: "NL",
    acronym: "NLD",
    code: "528",
  },
  {
    id: 93,
    name: "Honduras",
    initials: "HN",
    acronym: "HND",
    code: "340",
  },
  {
    id: 94,
    name: "Hong Kong",
    initials: "HK",
    acronym: "HKG",
    code: "344",
  },
  {
    id: 95,
    name: "Hungria",
    initials: "HU",
    acronym: "HUN",
    code: "348",
  },
  {
    id: 96,
    name: "Iêmen",
    initials: "YE",
    acronym: "YEM",
    code: "887",
  },
  {
    id: 97,
    name: "Ilha Bouvet (Território da Noruega)",
    initials: "BV",
    acronym: "BVT",
    code: "074",
  },
  {
    id: 98,
    name: "Ilha do Homem",
    initials: "IM",
    acronym: "IMN",
    code: "833",
  },
  {
    id: 99,
    name: "Ilha Natal",
    initials: "CX",
    acronym: "CXR",
    code: "162",
  },
  {
    id: 100,
    name: "Ilha Pitcairn",
    initials: "PN",
    acronym: "PCN",
    code: "612",
  },
  {
    id: 101,
    name: "Ilha Reunião",
    initials: "RE",
    acronym: "REU",
    code: "638",
  },
  {
    id: 102,
    name: "Ilhas Aland",
    initials: "AX",
    acronym: "ALA",
    code: "248",
  },
  {
    id: 103,
    name: "Ilhas Cayman",
    initials: "KY",
    acronym: "CYM",
    code: "136",
  },
  {
    id: 104,
    name: "Ilhas Cocos",
    initials: "CC",
    acronym: "CCK",
    code: "166",
  },
  {
    id: 105,
    name: "Ilhas Comores",
    initials: "KM",
    acronym: "COM",
    code: "174",
  },
  {
    id: 106,
    name: "Ilhas Cook",
    initials: "CK",
    acronym: "COK",
    code: "184",
  },
  {
    id: 107,
    name: "Ilhas Faroes",
    initials: "FO",
    acronym: "FRO",
    code: "234",
  },
  {
    id: 108,
    name: "Ilhas Falkland (Malvinas)",
    initials: "FK",
    acronym: "FLK",
    code: "238",
  },
  {
    id: 109,
    name: "Ilhas Geórgia do Sul e Sandwich do Sul",
    initials: "GS",
    acronym: "SGS",
    code: "239",
  },
  {
    id: 110,
    name: "Ilhas Heard e McDonald (Território da Austrália)",
    initials: "HM",
    acronym: "HMD",
    code: "334",
  },
  {
    id: 111,
    name: "Ilhas Marianas do Norte",
    initials: "MP",
    acronym: "MNP",
    code: "580",
  },
  {
    id: 112,
    name: "Ilhas Marshall",
    initials: "MH",
    acronym: "MHL",
    code: "584",
  },
  {
    id: 113,
    name: "Ilhas Menores dos Estados Unidos",
    initials: "UM",
    acronym: "UMI",
    code: "581",
  },
  {
    id: 114,
    name: "Ilhas Norfolk",
    initials: "NF",
    acronym: "NFK",
    code: "574",
  },
  {
    id: 115,
    name: "Ilhas Seychelles",
    initials: "SC",
    acronym: "SYC",
    code: "690",
  },
  {
    id: 116,
    name: "Ilhas Solomão",
    initials: "SB",
    acronym: "SLB",
    code: "090",
  },
  {
    id: 117,
    name: "Ilhas Svalbard e Jan Mayen",
    initials: "SJ",
    acronym: "SJM",
    code: "744",
  },
  {
    id: 118,
    name: "Ilhas Tokelau",
    initials: "TK",
    acronym: "TKL",
    code: "772",
  },
  {
    id: 119,
    name: "Ilhas Turks e Caicos",
    initials: "TC",
    acronym: "TCA",
    code: "796",
  },
  {
    id: 120,
    name: "Ilhas Virgens (Estados Unidos)",
    initials: "VI",
    acronym: "VIR",
    code: "850",
  },
  {
    id: 121,
    name: "Ilhas Virgens (Inglaterra)",
    initials: "VG",
    acronym: "VGB",
    code: "092",
  },
  {
    id: 122,
    name: "Ilhas Wallis e Futuna",
    initials: "WF",
    acronym: "WLF",
    code: "876",
  },
  {
    id: 123,
    name: "índia",
    initials: "IN",
    acronym: "IND",
    code: "356",
  },
  {
    id: 124,
    name: "Indonésia",
    initials: "ID",
    acronym: "IDN",
    code: "360",
  },
  {
    id: 125,
    name: "Irã",
    initials: "IR",
    acronym: "IRN",
    code: "364",
  },
  {
    id: 126,
    name: "Iraque",
    initials: "IQ",
    acronym: "IRQ",
    code: "368",
  },
  {
    id: 127,
    name: "Irlanda",
    initials: "IE",
    acronym: "IRL",
    code: "372",
  },
  {
    id: 128,
    name: "Islândia",
    initials: "IS",
    acronym: "ISL",
    code: "352",
  },
  {
    id: 129,
    name: "Israel",
    initials: "IL",
    acronym: "ISR",
    code: "376",
  },
  {
    id: 130,
    name: "Itália",
    initials: "IT",
    acronym: "ITA",
    code: "380",
  },
  {
    id: 131,
    name: "Jamaica",
    initials: "JM",
    acronym: "JAM",
    code: "388",
  },
  {
    id: 132,
    name: "Japão",
    initials: "JP",
    acronym: "JPN",
    code: "392",
  },
  {
    id: 133,
    name: "Jersey",
    initials: "JE",
    acronym: "JEY",
    code: "832",
  },
  {
    id: 134,
    name: "Jordânia",
    initials: "JO",
    acronym: "JOR",
    code: "400",
  },
  {
    id: 135,
    name: "Kênia",
    initials: "KE",
    acronym: "KEN",
    code: "404",
  },
  {
    id: 136,
    name: "Kiribati",
    initials: "KI",
    acronym: "KIR",
    code: "296",
  },
  {
    id: 137,
    name: "Kuait",
    initials: "KW",
    acronym: "KWT",
    code: "414",
  },
  {
    id: 138,
    name: "Laos",
    initials: "LA",
    acronym: "LAO",
    code: "418",
  },
  {
    id: 139,
    name: "Látvia",
    initials: "LV",
    acronym: "LVA",
    code: "428",
  },
  {
    id: 140,
    name: "Lesoto",
    initials: "LS",
    acronym: "LSO",
    code: "426",
  },
  {
    id: 141,
    name: "Líbano",
    initials: "LB",
    acronym: "LBN",
    code: "422",
  },
  {
    id: 142,
    name: "Libéria",
    initials: "LR",
    acronym: "LBR",
    code: "430",
  },
  {
    id: 143,
    name: "Líbia",
    initials: "LY",
    acronym: "LBY",
    code: "434",
  },
  {
    id: 144,
    name: "Liechtenstein",
    initials: "LI",
    acronym: "LIE",
    code: "438",
  },
  {
    id: 145,
    name: "Lituânia",
    initials: "LT",
    acronym: "LTU",
    code: "440",
  },
  {
    id: 146,
    name: "Luxemburgo",
    initials: "LU",
    acronym: "LUX",
    code: "442",
  },
  {
    id: 147,
    name: "Macau",
    initials: "MO",
    acronym: "MAC",
    code: "446",
  },
  {
    id: 148,
    name: "Macedônia (República Yugoslava)",
    initials: "MK",
    acronym: "MKD",
    code: "807",
  },
  {
    id: 149,
    name: "Madagascar",
    initials: "MG",
    acronym: "MDG",
    code: "450",
  },
  {
    id: 150,
    name: "Malásia",
    initials: "MY",
    acronym: "MYS",
    code: "458",
  },
  {
    id: 151,
    name: "Malaui",
    initials: "MW",
    acronym: "MWI",
    code: "454",
  },
  {
    id: 152,
    name: "Maldivas",
    initials: "MV",
    acronym: "MDV",
    code: "462",
  },
  {
    id: 153,
    name: "Mali",
    initials: "ML",
    acronym: "MLI",
    code: "466",
  },
  {
    id: 154,
    name: "Malta",
    initials: "MT",
    acronym: "MLT",
    code: "470",
  },
  {
    id: 155,
    name: "Marrocos",
    initials: "MA",
    acronym: "MAR",
    code: "504",
  },
  {
    id: 156,
    name: "Martinica",
    initials: "MQ",
    acronym: "MTQ",
    code: "474",
  },
  {
    id: 157,
    name: "Maurício",
    initials: "MU",
    acronym: "MUS",
    code: "480",
  },
  {
    id: 158,
    name: "Mauritânia",
    initials: "MR",
    acronym: "MRT",
    code: "478",
  },
  {
    id: 159,
    name: "Mayotte",
    initials: "YT",
    acronym: "MYT",
    code: "175",
  },
  {
    id: 160,
    name: "México",
    initials: "MX",
    acronym: "MEX",
    code: "484",
  },
  {
    id: 161,
    name: "Micronésia",
    initials: "FM",
    acronym: "FSM",
    code: "583",
  },
  {
    id: 162,
    name: "Moçambique",
    initials: "MZ",
    acronym: "MOZ",
    code: "508",
  },
  {
    id: 163,
    name: "Moldova",
    initials: "MD",
    acronym: "MDA",
    code: "498",
  },
  {
    id: 164,
    name: "Mônaco",
    initials: "MC",
    acronym: "MCO",
    code: "492",
  },
  {
    id: 165,
    name: "Mongólia",
    initials: "MN",
    acronym: "MNG",
    code: "496",
  },
  {
    id: 166,
    name: "Montenegro",
    initials: "ME",
    acronym: "MNE",
    code: "499",
  },
  {
    id: 167,
    name: "Montserrat",
    initials: "MS",
    acronym: "MSR",
    code: "500",
  },
  {
    id: 168,
    name: "Myanma",
    initials: "MM",
    acronym: "MMR",
    code: "104",
  },
  {
    id: 169,
    name: "Namíbia",
    initials: "NA",
    acronym: "NAM",
    code: "516",
  },
  {
    id: 170,
    name: "Nauru",
    initials: "NR",
    acronym: "NRU",
    code: "520",
  },
  {
    id: 171,
    name: "Nepal",
    initials: "NP",
    acronym: "NPL",
    code: "524",
  },
  {
    id: 172,
    name: "Nicarágua",
    initials: "NI",
    acronym: "NIC",
    code: "558",
  },
  {
    id: 173,
    name: "Níger",
    initials: "NE",
    acronym: "NER",
    code: "562",
  },
  {
    id: 174,
    name: "Nigéria",
    initials: "NG",
    acronym: "NGA",
    code: "566",
  },
  {
    id: 175,
    name: "Niue",
    initials: "NU",
    acronym: "NIU",
    code: "570",
  },
  {
    id: 176,
    name: "Noruega",
    initials: "NO",
    acronym: "NOR",
    code: "578",
  },
  {
    id: 177,
    name: "Nova Caledônia",
    initials: "NC",
    acronym: "NCL",
    code: "540",
  },
  {
    id: 178,
    name: "Nova Zelândia",
    initials: "NZ",
    acronym: "NZL",
    code: "554",
  },
  {
    id: 179,
    name: "Omã",
    initials: "OM",
    acronym: "OMN",
    code: "512",
  },
  {
    id: 180,
    name: "Palau",
    initials: "PW",
    acronym: "PLW",
    code: "585",
  },
  {
    id: 181,
    name: "Panamá",
    initials: "PA",
    acronym: "PAN",
    code: "591",
  },
  {
    id: 182,
    name: "Papua-Nova Guiné",
    initials: "PG",
    acronym: "PNG",
    code: "598",
  },
  {
    id: 183,
    name: "Paquistão",
    initials: "PK",
    acronym: "PAK",
    code: "586",
  },
  {
    id: 184,
    name: "Paraguai",
    initials: "PY",
    acronym: "PRY",
    code: "600",
  },
  {
    id: 185,
    name: "Peru",
    initials: "PE",
    acronym: "PER",
    code: "604",
  },
  {
    id: 186,
    name: "Polinésia Francesa",
    initials: "PF",
    acronym: "PYF",
    code: "258",
  },
  {
    id: 187,
    name: "Polônia",
    initials: "PL",
    acronym: "POL",
    code: "616",
  },
  {
    id: 188,
    name: "Porto Rico",
    initials: "PR",
    acronym: "PRI",
    code: "630",
  },
  {
    id: 189,
    name: "Portugal",
    initials: "PT",
    acronym: "PRT",
    code: "620",
  },
  {
    id: 190,
    name: "Qatar",
    initials: "QA",
    acronym: "QAT",
    code: "634",
  },
  {
    id: 191,
    name: "Quirguistão",
    initials: "KG",
    acronym: "KGZ",
    code: "417",
  },
  {
    id: 192,
    name: "República Centro-Africana",
    initials: "CF",
    acronym: "CAF",
    code: "140",
  },
  {
    id: 193,
    name: "República Democrática do Congo",
    initials: "CD",
    acronym: "COD",
    code: "180",
  },
  {
    id: 194,
    name: "República Dominicana",
    initials: "DO",
    acronym: "DOM",
    code: "214",
  },
  {
    id: 195,
    name: "República Tcheca",
    initials: "CZ",
    acronym: "CZE",
    code: "203",
  },
  {
    id: 196,
    name: "Romênia",
    initials: "RO",
    acronym: "ROM",
    code: "642",
  },
  {
    id: 197,
    name: "Ruanda",
    initials: "RW",
    acronym: "RWA",
    code: "646",
  },
  {
    id: 198,
    name: "Rússia (antiga URSS) - Federação Russa",
    initials: "RU",
    acronym: "RUS",
    code: "643",
  },
  {
    id: 199,
    name: "Saara Ocidental",
    initials: "EH",
    acronym: "ESH",
    code: "732",
  },
  {
    id: 200,
    name: "Saint Vincente e Granadinas",
    initials: "VC",
    acronym: "VCT",
    code: "670",
  },
  {
    id: 201,
    name: "Samoa Americana",
    initials: "AS",
    acronym: "ASM",
    code: "016",
  },
  {
    id: 202,
    name: "Samoa Ocidental",
    initials: "WS",
    acronym: "WSM",
    code: "882",
  },
  {
    id: 203,
    name: "San Marino",
    initials: "SM",
    acronym: "SMR",
    code: "674",
  },
  {
    id: 204,
    name: "Santa Helena",
    initials: "SH",
    acronym: "SHN",
    code: "654",
  },
  {
    id: 205,
    name: "Santa Lúcia",
    initials: "LC",
    acronym: "LCA",
    code: "662",
  },
  {
    id: 206,
    name: "São Bartolomeu",
    initials: "BL",
    acronym: "BLM",
    code: "652",
  },
  {
    id: 207,
    name: "São Cristóvão e Névis",
    initials: "KN",
    acronym: "KNA",
    code: "659",
  },
  {
    id: 208,
    name: "São Martim",
    initials: "MF",
    acronym: "MAF",
    code: "663",
  },
  {
    id: 209,
    name: "São Tomé e Príncipe",
    initials: "ST",
    acronym: "STP",
    code: "678",
  },
  {
    id: 210,
    name: "Senegal",
    initials: "SN",
    acronym: "SEN",
    code: "686",
  },
  {
    id: 211,
    name: "Serra Leoa",
    initials: "SL",
    acronym: "SLE",
    code: "694",
  },
  {
    id: 212,
    name: "Sérvia",
    initials: "RS",
    acronym: "SRB",
    code: "688",
  },
  {
    id: 213,
    name: "Síria",
    initials: "SY",
    acronym: "SYR",
    code: "760",
  },
  {
    id: 214,
    name: "Somália",
    initials: "SO",
    acronym: "SOM",
    code: "706",
  },
  {
    id: 215,
    name: "Sri Lanka",
    initials: "LK",
    acronym: "LKA",
    code: "144",
  },
  {
    id: 216,
    name: "St. Pierre and Miquelon",
    initials: "PM",
    acronym: "SPM",
    code: "666",
  },
  {
    id: 217,
    name: "Suazilândia",
    initials: "SZ",
    acronym: "SWZ",
    code: "748",
  },
  {
    id: 218,
    name: "Sudão",
    initials: "SD",
    acronym: "SDN",
    code: "736",
  },
  {
    id: 219,
    name: "Suécia",
    initials: "SE",
    acronym: "SWE",
    code: "752",
  },
  {
    id: 220,
    name: "Suíça",
    initials: "CH",
    acronym: "CHE",
    code: "756",
  },
  {
    id: 221,
    name: "Suriname",
    initials: "SR",
    acronym: "SUR",
    code: "740",
  },
  {
    id: 222,
    name: "Tadjiquistão",
    initials: "TJ",
    acronym: "TJK",
    code: "762",
  },
  {
    id: 223,
    name: "Tailândia",
    initials: "TH",
    acronym: "THA",
    code: "764",
  },
  {
    id: 224,
    name: "Taiwan",
    initials: "TW",
    acronym: "TWN",
    code: "158",
  },
  {
    id: 225,
    name: "Tanzânia",
    initials: "TZ",
    acronym: "TZA",
    code: "834",
  },
  {
    id: 226,
    name: "Território Britânico do Oceano índico",
    initials: "IO",
    acronym: "IOT",
    code: "086",
  },
  {
    id: 227,
    name: "Territórios do Sul da França",
    initials: "TF",
    acronym: "ATF",
    code: "260",
  },
  {
    id: 228,
    name: "Territórios Palestinos Ocupados",
    initials: "PS",
    acronym: "PSE",
    code: "275",
  },
  {
    id: 229,
    name: "Timor Leste",
    initials: "TP",
    acronym: "TMP",
    code: "626",
  },
  {
    id: 230,
    name: "Togo",
    initials: "TG",
    acronym: "TGO",
    code: "768",
  },
  {
    id: 231,
    name: "Tonga",
    initials: "TO",
    acronym: "TON",
    code: "776",
  },
  {
    id: 232,
    name: "Trinidad and Tobago",
    initials: "TT",
    acronym: "TTO",
    code: "780",
  },
  {
    id: 233,
    name: "Tunísia",
    initials: "TN",
    acronym: "TUN",
    code: "788",
  },
  {
    id: 234,
    name: "Turcomenistão",
    initials: "TM",
    acronym: "TKM",
    code: "795",
  },
  {
    id: 235,
    name: "Turquia",
    initials: "TR",
    acronym: "TUR",
    code: "792",
  },
  {
    id: 236,
    name: "Tuvalu",
    initials: "TV",
    acronym: "TUV",
    code: "798",
  },
  {
    id: 237,
    name: "Ucrânia",
    initials: "UA",
    acronym: "UKR",
    code: "804",
  },
  {
    id: 238,
    name: "Uganda",
    initials: "UG",
    acronym: "UGA",
    code: "800",
  },
  {
    id: 239,
    name: "Uruguai",
    initials: "UY",
    acronym: "URY",
    code: "858",
  },
  {
    id: 240,
    name: "Uzbequistão",
    initials: "UZ",
    acronym: "UZB",
    code: "860",
  },
  {
    id: 241,
    name: "Vanuatu",
    initials: "VU",
    acronym: "VUT",
    code: "548",
  },
  {
    id: 242,
    name: "Vaticano",
    initials: "VA",
    acronym: "VAT",
    code: "336",
  },
  {
    id: 243,
    name: "Venezuela",
    initials: "VE",
    acronym: "VEN",
    code: "862",
  },
  {
    id: 244,
    name: "Vietnã",
    initials: "VN",
    acronym: "VNM",
    code: "704",
  },
  {
    id: 245,
    name: "Zâmbia",
    initials: "ZM",
    acronym: "ZMB",
    code: "894",
  },
  {
    id: 246,
    name: "Zimbábue",
    initials: "ZW",
    acronym: "ZWE",
    code: "716",
  },
];
