name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git for GitHub
        run: |
          git config --global user.email "samuelaoliveiraramos@gmail.com"
          git config --global user.name "Samuel Ramos"
          git config --global push.default simple
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/samuelrms/br-states-flags.git

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Run standard-version
        run: npx standard-version

      - name: Commit changes
        run: |
          git add -A
          git commit -m "chore: release new version"

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes
        run: git push origin main
