name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create temporary branch
        run: git checkout -b release

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Configure Git
        run: |
          git config --global user.email "samuelaoliveiraramos@gmail.com"
          git config --global user.name "Samuel Ramos"

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Run standard-version
        run: npx standard-version

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main
          base: release
          title: "Release updates"
          body: "This pull request includes version updates and release changes."
          token: ${{ secrets.GITHUB_TOKEN }}
